 version: '2'
 services:
  jboss:
   image: jboss-eap-mysql-centos-jdk1.7
  #container_name: jboss1
   volumes:
       - "./.data/jboss/logs:/opt/jboss-eap-6.4/standalone/log"
       - "./.data/jboss/deployments:/opt/jboss-eap-6.4/standalone/deployments"
   depends_on:
      - db
  #ports:
   # - 8009:8009
    #- 8080:8080
    #- 9990:9990
   expose:
       - 8080
       - 8009
       - 9990 

  db:
     image: docker.io/mysql/mysql-server 
     container_name: mysql
     volumes:
       - "./.data/db:/var/lib/mysql"
     ports:
       - "3306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: test2
       MYSQL_USER: admin
       MYSQL_PASSWORD: 123456
